# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '性价比优选.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton)
import requests
import optparse
import json

class xjb(QMainWindow):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(929, 405)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(80, 60, 131, 41))
        self.pushButton.setStyleSheet("\n"
"border-style:none;\n"
"padding:11px;\n"
"border-radius:3px;\n"
"background:transparent;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 50, 151, 61))
        self.pushButton_2.setStyleSheet("\n"
"border-style:none;\n"
"padding:11px;\n"
"border-radius:3px;\n"
"background:transparent;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(440, 50, 161, 71))
        self.pushButton_3.setStyleSheet("\n"
"border-style:none;\n"
"padding:11px;\n"
"border-radius:3px;\n"
"background:transparent;")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(660, 50, 171, 71))
        self.pushButton_4.setStyleSheet("\n"
"border-style:none;\n"
"padding:11px;\n"
"border-radius:3px;\n"
"background:transparent;")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, -80, 911, 551))
        self.label.setStyleSheet("image: url(:/955/photo/27a0ce800e118b09d51f4c0e7bc7cdbd.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(60, 130, 771, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 6, item)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(450, 50, 221, 101))
        self.label_4.setStyleSheet("image: url(:/955/photo/资源 4xxhdpi.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(650, 50, 221, 101))
        self.label_5.setStyleSheet("image: url(:/955/photo/资源 5xxhdpi.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(250, 50, 221, 101))
        self.label_6.setStyleSheet("image: url(:/955/photo/资源 3xxhdpi.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(50, 50, 181, 81))
        self.label_7.setStyleSheet("image: url(:/955/photo/资源 1xxhdpi.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(Form)
        self.tableWidget_2.setGeometry(QtCore.QRect(60, 130, 771, 211))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 6, item)
        self.tableWidget_2.raise_()
        self.label.raise_()
        self.tableWidget.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(self.pushButton.show)
        self.pushButton_2.clicked.connect(self.pushButton_2.show)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "性价比优选"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "NO.1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "NO.2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "NO.3"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "NO.4"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "NO.5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "店名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "星级"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "地址"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "联系方式"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "点评数"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "人均消费"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "顾客评分"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "韩一品"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", "5.0"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Form", "70国道闽江学院东门（近小黑酒吧）"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("Form", "13290985085"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("Form", "206"))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("Form", "23"))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("Form", "9.1"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "关中往事"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Form", "5.0"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Form", "柳河路81号"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("Form", "0591-83720468"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("Form", "478"))
        item = self.tableWidget.item(2, 5)
        item.setText(_translate("Form", "32"))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("Form", "9.1"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "SUBWAY赛百味"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Form", "5.0"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Form", "东街主路38-1号"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("Form", "0591-87315356"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("Form", "449"))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("Form", "30"))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("Form", "9.1"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Form", "没牙伯花生汤店"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Form", "4.5"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("Form", "老药洲街182号（新亚细亚南台农贸市场旁）"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("Form", "13705080687"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("Form", "1828"))
        item = self.tableWidget.item(4, 5)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.item(4, 6)
        item.setText(_translate("Form", "8.6"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Form", "狮诚记(道山西路店)"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Form", "4.5"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("Form", "道山西路88号"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("Form", "0591-22855513"))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("Form", "607"))
        item = self.tableWidget.item(5, 5)
        item.setText(_translate("Form", "42"))
        item = self.tableWidget.item(5, 6)
        item.setText(_translate("Form", "8.7"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "性价比优选"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "NO.1"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "NO.2"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "NO.3"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Form", "NO.4"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("Form", "NO.5"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "店名"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "星级"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "地址"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "联系方式"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "点评数"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "人均消费"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Form", "顾客评分"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("Form", "韩一品222"))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("Form", "5.0"))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("Form", "70国道闽江学院东门（近小黑酒吧）"))
        item = self.tableWidget_2.item(1, 3)
        item.setText(_translate("Form", "13290985085"))
        item = self.tableWidget_2.item(1, 4)
        item.setText(_translate("Form", "206"))
        item = self.tableWidget_2.item(1, 5)
        item.setText(_translate("Form", "23"))
        item = self.tableWidget_2.item(1, 6)
        item.setText(_translate("Form", "9.1"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("Form", "关中往事"))
        item = self.tableWidget_2.item(2, 1)
        item.setText(_translate("Form", "5.0"))
        item = self.tableWidget_2.item(2, 2)
        item.setText(_translate("Form", "柳河路81号"))
        item = self.tableWidget_2.item(2, 3)
        item.setText(_translate("Form", "0591-83720468"))
        item = self.tableWidget_2.item(2, 4)
        item.setText(_translate("Form", "478"))
        item = self.tableWidget_2.item(2, 5)
        item.setText(_translate("Form", "32"))
        item = self.tableWidget_2.item(2, 6)
        item.setText(_translate("Form", "9.1"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("Form", "SUBWAY赛百味"))
        item = self.tableWidget_2.item(3, 1)
        item.setText(_translate("Form", "5.0"))
        item = self.tableWidget_2.item(3, 2)
        item.setText(_translate("Form", "东街主路38-1号"))
        item = self.tableWidget_2.item(3, 3)
        item.setText(_translate("Form", "0591-87315356"))
        item = self.tableWidget_2.item(3, 4)
        item.setText(_translate("Form", "449"))
        item = self.tableWidget_2.item(3, 5)
        item.setText(_translate("Form", "30"))
        item = self.tableWidget_2.item(3, 6)
        item.setText(_translate("Form", "9.1"))
        item = self.tableWidget_2.item(4, 0)
        item.setText(_translate("Form", "没牙伯花生汤店"))
        item = self.tableWidget_2.item(4, 1)
        item.setText(_translate("Form", "4.5"))
        item = self.tableWidget_2.item(4, 2)
        item.setText(_translate("Form", "老药洲街182号（新亚细亚南台农贸市场旁）"))
        item = self.tableWidget_2.item(4, 3)
        item.setText(_translate("Form", "13705080687"))
        item = self.tableWidget_2.item(4, 4)
        item.setText(_translate("Form", "1828"))
        item = self.tableWidget_2.item(4, 5)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_2.item(4, 6)
        item.setText(_translate("Form", "8.6"))
        item = self.tableWidget_2.item(5, 0)
        item.setText(_translate("Form", "狮诚记(道山西路店)"))
        item = self.tableWidget_2.item(5, 1)
        item.setText(_translate("Form", "4.5"))
        item = self.tableWidget_2.item(5, 2)
        item.setText(_translate("Form", "道山西路88号"))
        item = self.tableWidget_2.item(5, 3)
        item.setText(_translate("Form", "0591-22855513"))
        item = self.tableWidget_2.item(5, 4)
        item.setText(_translate("Form", "607"))
        item = self.tableWidget_2.item(5, 5)
        item.setText(_translate("Form", "42"))
        item = self.tableWidget_2.item(5, 6)
        item.setText(_translate("Form", "8.7"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
import photo
if __name__ == "__main__":
    import sys
    from PyQt5.QtGui import QIcon

    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(widget)
    widget.setWindowIcon(QIcon('web.png'))  # 增加icon图标，如果没有图片可以没有这句
    widget.show()
    sys.exit(app.exec_())